download data from: https://www.cdc.gov/brfss/annual_data/2023/files/LLCP2023XPT.zip

In [1]:
import pandas as pd
import numpy as np

df_all = pd.read_sas(
    "../data/LLCP2023.XPT",
    format="xport"
)

In [2]:
df_all.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,b'03012023',b'03',b'01',b'2023',1100.0,b'2023000001',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
1,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000002',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,b'03082023',b'03',b'08',b'2023',1100.0,b'2023000003',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,b'03062023',b'03',b'06',b'2023',1100.0,b'2023000004',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000005',2.023000e+09,1.0,...,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,2.0,1.0,1.0,2.0

In [54]:
df = df_all.copy()

In [55]:
df = df.loc[:,["CVDINFR4", "CVDCRHD4", "CHECKUP1", "HAVARTH4", "BPHIGH6", "TOLDHI3", "SMOKE100", "SMOKDAY2", "_BMI5", "EXERANY2", "ALCDAY4", "_AGE_G", "_SEX", "GENHLTH", "PHYSHLTH", "MENTHLTH", "POORHLTH", "ASTHMA3","CHCSCNC1", "CHCCOPD3", "CHCKDNY2", "DIABETE4", "CVDSTRK3", "DIFFWALK"]]
df.head()

,CVDINFR4,CVDCRHD4,CHECKUP1,HAVARTH4,BPHIGH6,TOLDHI3,SMOKE100,SMOKDAY2,_BMI5,EXERANY2,...,PHYSHLTH,MENTHLTH,POORHLTH,ASTHMA3,CHCSCNC1,CHCCOPD3,CHCKDNY2,DIABETE4,CVDSTRK3,DIFFWALK
0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,3047.0,2.0,...,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0
1,2.0,2.0,2.0,1.0,1.0,1.0,2.0,NaN,2856.0,1.0,...,88.0,88.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0,2.0
2,2.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,2231.0,1.0,...,6.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0,1.0
3,2.0,2.0,3.0,1.0,3.0,2.0,2.0,NaN,2744.0,1.0,...,2.0,88.0,88.0,2.0,1.0,2.0,2.0,3.0,2.0,1.0
4,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2585.0,1.0,...,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0

In [56]:
# rename columns
rename_map = {
    # Outcomes
    "CVDINFR4": "ever_heart_attack",
    "CVDCRHD4": "ever_coronary_heart_disease",

    # Clinical risk factors
    "BPHIGH6": "high_blood_pressure",
    "TOLDHI3": "high_cholesterol",
    "DIABETE4": "diabetes",
    "_BMI5": "bmi_x100",
    "DIFFWALK": "difficulty_walking",

    # Smoking
    "SMOKE100": "ever_smoked_100_cigs",
    "SMOKDAY2": "current_smoking_status",

    # Lifestyle
    "EXERANY2": "exercise_past_30_days",
    "ALCDAY4": "alcohol_days_per_month",
    "CHECKUP1": "last_checkup",

    # Demographics
    "_AGE_G": "age_group",
    "_SEX": "sex",

    # Self-rated health
    "GENHLTH": "general_health",
    "PHYSHLTH": "poor_physical_health_days",
    "MENTHLTH": "poor_mental_health_days",
    "POORHLTH": "activity_limited_health_days",

    # Comorbidities
    "ASTHMA3": "current_asthma",
    "CHCSCNC1": "skin_cancer_history",
    "CHCCOPD3": "copd_history",
    "CHCKDNY2": "kidney_disease_history",
    "CVDSTRK3": "stroke_history",
    "HAVARTH4": "arthritis",
}
df = df.rename(columns=rename_map)
df.head()

,ever_heart_attack,ever_coronary_heart_disease,last_checkup,arthritis,high_blood_pressure,high_cholesterol,ever_smoked_100_cigs,current_smoking_status,bmi_x100,exercise_past_30_days,...,poor_physical_health_days,poor_mental_health_days,activity_limited_health_days,current_asthma,skin_cancer_history,copd_history,kidney_disease_history,diabetes,stroke_history,difficulty_walking
0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,3047.0,2.0,...,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0
1,2.0,2.0,2.0,1.0,1.0,1.0,2.0,NaN,2856.0,1.0,...,88.0,88.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0,2.0
2,2.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,2231.0,1.0,...,6.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0,1.0
3,2.0,2.0,3.0,1.0,3.0,2.0,2.0,NaN,2744.0,1.0,...,2.0,88.0,88.0,2.0,1.0,2.0,2.0,3.0,2.0,1.0
4,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,2585.0,1.0,...,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0

In [57]:
df["any_cvd"] = (
    (df["ever_heart_attack"] == 1) |
    (df["ever_coronary_heart_disease"] == 1) 
).astype(int)

In [58]:
df["arthritis"] = df["arthritis"].replace({
    1: 1,
    2: 0,
    7: np.nan,
    9: np.nan
})

In [59]:
checkup_map = {
    1: "≤1 year",
    2: "1–2 years",
    3: "2–5 years",
    4: "≥5 years",
    7: np.nan,
    9: np.nan
}

df["checkup_recency"] = df["last_checkup"].map(checkup_map)
df = df.drop("last_checkup", axis=1)

In [60]:
# walking difficulty
df["difficulty_walking"] = df["difficulty_walking"].replace({
    1: 1,
    2: 0,
    7: np.nan,
    9: np.nan
}).astype(float)

In [61]:
def recode_binary(series):
    return (
        series
        .replace({
            1: 1,
            2: 0,
            7: np.nan,
            9: np.nan,
            77: np.nan,
            88: np.nan,
            99: np.nan
        })
        .astype("float")
    )

In [62]:
binary_vars = [
    "ever_heart_attack",
    "ever_coronary_heart_disease",
    "ever_smoked_100_cigs",
    "exercise_past_30_days",
    "current_asthma",
    "skin_cancer_history",
    "copd_history",
    "kidney_disease_history",
    "stroke_history",
    "difficulty_walking",
    "high_cholesterol"
]

for v in binary_vars:
    df[v] = recode_binary(df[v])
df[binary_vars] = df[binary_vars].astype("Int64")

In [63]:
df["any_cvd"].value_counts()

any_cvd
0    397012
1     36311
Name: count, dtype: int64

In [64]:
# Smoking
df["current_smoker"] = np.nan

# If smokes now → smoker
df.loc[df["current_smoking_status"].isin([1, 2]), "current_smoker"] = 1

# If does not smoke now → non-smoker
df.loc[df["current_smoking_status"] == 3, "current_smoker"] = 0

# If never smoked ≥100 cigarettes → non-smoker
df.loc[df["ever_smoked_100_cigs"] == 0, "current_smoker"] = 0

# Explicit missing codes
df.loc[
    df["current_smoking_status"].isin([7, 9]) |
    df["ever_smoked_100_cigs"].isin([7, 9]),
    "current_smoker"
] = np.nan
df = df.drop("current_smoking_status", axis=1)

In [65]:
# Days: health, mental health
def recode_days(s):
    return s.replace({
        88: 0,
        77: np.nan,
        99: np.nan
    })
df["poor_physical_health_days"] = recode_days(
    df["poor_physical_health_days"])
df["poor_mental_health_days"] = recode_days(
    df["poor_mental_health_days"])
df["activity_limited_health_days"] = recode_days(
    df["poor_physical_health_days"])

In [66]:
# BMI
df["bmi"] = round(df["bmi_x100"]/100,2)
df = df.drop("bmi_x100", axis=1)

In [67]:
# Sex at birth
df["sex"] = df["sex"].replace({
    1: "Male",
    2: "Female"
})

In [68]:
# Age group
age_map = {
    1: "18-24",
    2: "25-29",
    3: "30-34",
    4: "35-39",
    5: "40-44",
    6: "45-49",
    7: "50-54",
    8: "55-59",
    9: "60-64",
    10: "65-69",
    11: "70-74",
    12: "75-79",
    13: "80+"
}

df["age_group"] = df["age_group"].map(age_map)

In [69]:
# general health
genhlth_map = {
    1: "Excellent",
    2: "Very good",
    3: "Good",
    4: "Fair",
    5: "Poor",
    7: np.nan,
    9: np.nan,
}

df["general_health_label"] = df["general_health"].replace(genhlth_map)
df.loc[df["general_health_label"].isin([7, 9]), "general_health"] = np.nan
df = df.drop("general_health", axis=1)

In [70]:
# blood pressure: suggestion for ML: use both during pregnancy and borderline as yes
df["high_blood_pressure_label"] = df["high_blood_pressure"].replace({
    1: "Yes",
    2: "Yes, during pregnancy",
    3: "No",
    4: "No, but Borderline",
    7: np.nan,
    9: np.nan
})
df = df.drop("high_blood_pressure", axis=1)

In [71]:
# diabetes: suggestion for ML: use both during pregnancy and borderline as yes
df["diabetes_label"] = df["diabetes"].replace({
    1: "Yes",
    2: "Yes, during pregnancy",
    3: "No",
    4: "No, but Borderline",
    7: np.nan,
    9: np.nan
})
df = df.drop("diabetes", axis=1)

In [72]:
# Alcoholdays/month
def alc_days_per_month(val):
    if val in [777, 999]:
        return np.nan
    elif val == 888:
        return 0
    elif 1 <= val <= 30:
        return val  # already monthly
    elif 101 <= val <= 199:
        # weekly drinking: subtract 100 to get days/week, multiply by 4
        return round((val - 100) * 4.3)
    else:
        return np.nan  # other unexpected codes

df["alcohol_days_month"] = df["alcohol_days_per_month"].apply(alc_days_per_month)
df = df.drop("alcohol_days_per_month", axis=1)

In [73]:
df.sample(12)

,ever_heart_attack,ever_coronary_heart_disease,arthritis,high_cholesterol,ever_smoked_100_cigs,exercise_past_30_days,age_group,sex,poor_physical_health_days,poor_mental_health_days,...,stroke_history,difficulty_walking,any_cvd,checkup_recency,current_smoker,bmi,general_health_label,high_blood_pressure_label,diabetes_label,alcohol_days_month
427977,0,0,0.0,0,1,0,35-39,Female,0.0,0.0,...,0,0,0,≤1 year,0.0,28.32,Good,Yes,No,NaN
363567,0,0,0.0,<NA>,0,1,18-24,Female,7.0,14.0,...,0,0,0,≤1 year,0.0,19.37,Good,No,No,9.0
125599,0,0,1.0,0,1,0,45-49,Female,20.0,0.0,...,0,1,0,≤1 year,0.0,44.93,Fair,Yes,No,NaN
391931,0,0,1.0,1,1,1,45-49,Male,15.0,20.0,...,0,1,0,≤1 year,0.0,28.89,Good,Yes,No,NaN
215091,0,0,NaN,1,0,1,45-49,Male,0.0,0.0,...,0,0,0,≤1 year,0.0,25.99,Very good,No,"No, but Borderline",17.0
143891,0,0,1.0,1,0,1,40-44,Male,0.0,0.0,...,0,0,0,≤1 year,0.0,26.87,Very good,No,No,NaN
184011,0,0,0.0,<NA>,1,1,25-29,Female,5.0,15.0,...,0,0,0,≤1 year,0.0,20.97,Fair,No,No,NaN
184500,0,0,0.0,1,<NA>,1,45-49,Female,0.0,0.0,...,0,0,0,≤1 year,NaN,21.28,Very good,No,No,0.0
391867,0,0,0.0,<NA>,0,1,18-24,Male,0.0,1.0,...,0,0,0,2–5 years,0.0,21.63,Good,No,No,4.0
56191,0,0,0.0,0,0,1,30-34,Female,5.0,2.0,...,0,0,0,1–2 years,0.0,21.97,Very good,Yes,No,NaN
411565,0,0,0.0,0,<NA>,0,40-44,Female,0.0,0.0,...,0,0,0,≤1 year,NaN,31.89,Good,Yes,No,NaN
220632,1,0,1.0,0,0,1,40-44,Male,30.0,0.0,...,0,1,1,≤1 year,0.0,33.47,Fair,No,Yes,0.0

In [74]:
df.shape

(433323, 25)

In [ ]:
# drop rows with missing label
df = df.dropna(subset=["ever_heart_attack"])

In [77]:
df.shape

(430755, 25)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 430755 entries, 0 to 433322
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   ever_heart_attack             430755 non-null  Int64
 1   ever_coronary_heart_disease   427159 non-null  Int64
 2   arthritis                     428503 non-null  float64
 3   high_cholesterol              376398 non-null  Int64
 4   ever_smoked_100_cigs          408539 non-null  Int64
 5   exercise_past_30_days         429589 non-null  Int64
 6   age_group                     430755 non-null  object
 7   sex                           430755 non-null  object
 8   poor_physical_health_days     420255 non-null  float64
 9   poor_mental_health_days       422854 non-null  float64
 10  activity_limited_health_days  420255 non-null  float64
 11  current_asthma                429333 non-null  Int64
 12  skin_cancer_history           428148 non-null  Int64
 13  copd_history                  429014 non-null  Int64
 14  kidney_disease_history        429146 non-null  Int64
 15  stroke_history                429681 non-null  Int64
 16  difficulty_walking            413200 non-null  Int64
 17  any_cvd                       430755 non-null  int64
 18  checkup_recency               422407 non-null  object
 19  current_smoker                408048 non-null  float64
 20  bmi                           390751 non-null  float64
 21  general_health_label          429562 non-null  object
 22  high_blood_pressure_label     429041 non-null  object
 23  diabetes_label                430005 non-null  object
 24  alcohol_days_month            262385 non-null  float64
dtypes: Int64(11), float64(7), int64(1), object(6)
memory usage: 90.0+ MB

In [79]:
df.to_csv("../data/brfss_2023_heart_risk_clean_extended.csv", index=False)