download data from: https://www.cdc.gov/brfss/annual_data/2023/files/LLCP2023XPT.zip

In [ ]:
import pandas as pd

df_all = pd.read_sas(
    "../data/LLCP2023.XPT",
    format="xport"
)

In [ ]:
df_all.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,b'03012023',b'03',b'01',b'2023',1100.0,b'2023000001',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
1,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000002',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,b'03082023',b'03',b'08',b'2023',1100.0,b'2023000003',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,b'03062023',b'03',b'06',b'2023',1100.0,b'2023000004',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000005',2.023000e+09,1.0,...,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,2.0,1.0,1.0,2.0

In [ ]:
df = df_all.copy()

In [ ]:
df = df.loc[:,["CVDINFR4", "BPHIGH6", "TOLDHI3", "SMOKE100", "SMOKDAY2", "_BMI5", "EXERANY2", "ALCDAY4", "_AGE_G", "_SEX", "GENHLTH", "PHYSHLTH", "MENTHLTH", "POORHLTH", "ASTHMA3","CHCSCNC1", "CHCCOPD3", "CHCKDNY2", "DIABETE4", "CVDSTRK3"]]
df.head()

,CVDINFR4,BPHIGH6,TOLDHI3,SMOKE100,SMOKDAY2,_BMI5,EXERANY2,ALCDAY4,_AGE_G,_SEX,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,ASTHMA3,CHCSCNC1,CHCCOPD3,CHCKDNY2,DIABETE4,CVDSTRK3
0,2.0,1.0,2.0,2.0,NaN,3047.0,2.0,888.0,6.0,2.0,2.0,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0
1,2.0,1.0,1.0,2.0,NaN,2856.0,1.0,888.0,6.0,2.0,2.0,88.0,88.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0
2,2.0,1.0,1.0,1.0,3.0,2231.0,1.0,888.0,6.0,2.0,4.0,6.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0
3,2.0,3.0,2.0,2.0,NaN,2744.0,1.0,888.0,6.0,2.0,2.0,2.0,88.0,88.0,2.0,1.0,2.0,2.0,3.0,2.0
4,2.0,1.0,2.0,2.0,NaN,2585.0,1.0,202.0,6.0,2.0,4.0,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0

In [ ]:
# rename columns
rename_map = {
    # Outcomes
    "CVDINFR4": "ever_heart_attack",

    # Clinical risk factors
    "BPHIGH6": "high_blood_pressure",
    "TOLDHI3": "high_cholesterol",
    "DIABETE4": "diabetes",
    "_BMI5": "bmi_x100",

    # Smoking
    "SMOKE100": "ever_smoked_100_cigs",
    "SMOKDAY2": "current_smoking_status",

    # Lifestyle
    "EXERANY2": "exercise_past_30_days",
    "ALCDAY4": "alcohol_days_per_month",

    # Demographics
    "_AGE_G": "age_group",
    "_SEX": "sex",

    # Self-rated health
    "GENHLTH": "general_health",
    "PHYSHLTH": "poor_physical_health_days",
    "MENTHLTH": "poor_mental_health_days",
    "POORHLTH": "activity_limited_health_days",

    # Comorbidities
    "ASTHMA3": "current_asthma",
    "CHCSCNC1": "skin_cancer_history",
    "CHCCOPD3": "copd_history",
    "CHCKDNY2": "kidney_disease_history",
    "CVDSTRK3": "stroke_history",
}
df = df.rename(columns=rename_map)
df.head()

,ever_heart_attack,high_blood_pressure,high_cholesterol,ever_smoked_100_cigs,current_smoking_status,bmi_x100,exercise_past_30_days,alcohol_days_per_month,age_group,sex,general_health,poor_physical_health_days,poor_mental_health_days,activity_limited_health_days,current_asthma,skin_cancer_history,copd_history,kidney_disease_history,diabetes,stroke_history
0,2.0,1.0,2.0,2.0,NaN,3047.0,2.0,888.0,6.0,2.0,2.0,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0
1,2.0,1.0,1.0,2.0,NaN,2856.0,1.0,888.0,6.0,2.0,2.0,88.0,88.0,NaN,2.0,2.0,2.0,2.0,3.0,2.0
2,2.0,1.0,1.0,1.0,3.0,2231.0,1.0,888.0,6.0,2.0,4.0,6.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,2.0
3,2.0,3.0,2.0,2.0,NaN,2744.0,1.0,888.0,6.0,2.0,2.0,2.0,88.0,88.0,2.0,1.0,2.0,2.0,3.0,2.0
4,2.0,1.0,2.0,2.0,NaN,2585.0,1.0,202.0,6.0,2.0,4.0,88.0,88.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0

In [48]:
import numpy as np

def recode_binary(series):
    return (
        series
        .replace({
            1: 1,
            2: 0,
            7: np.nan,
            9: np.nan,
            77: np.nan,
            88: np.nan,
            99: np.nan
        })
        .astype("float")
    )

In [ ]:
binary_vars = [
    "ever_heart_attack",
    "ever_smoked_100_cigs",
    "exercise_past_30_days",
    "current_asthma",
    "skin_cancer_history",
    "copd_history",
    "kidney_disease_history",
    "stroke_history"
]

for v in binary_vars:
    df[v] = recode_binary(df[v])

In [75]:
# Smoking
df["current_smoker"] = np.nan

# If smokes now → smoker
df.loc[df["current_smoking_status"].isin([1, 2]), "current_smoker"] = 1

# If does not smoke now → non-smoker
df.loc[df["current_smoking_status"] == 3, "current_smoker"] = 0

# If never smoked ≥100 cigarettes → non-smoker
df.loc[df["ever_smoked_100_cigs"] == 0, "current_smoker"] = 0

# Explicit missing codes
df.loc[
    df["current_smoking_status"].isin([7, 9]) |
    df["ever_smoked_100_cigs"].isin([7, 9]),
    "current_smoker"
] = np.nan
df = df.drop("current_smoking_status", axis=1)

In [69]:
# Days: health, mental health
def recode_days(s):
    return s.replace({
        88: 0,
        77: np.nan,
        99: np.nan
    })
df["poor_physical_health_days"] = recode_days(
    df["poor_physical_health_days"])
df["poor_mental_health_days"] = recode_days(
    df["poor_mental_health_days"])
df["activity_limited_health_days"] = recode_days(
    df["poor_physical_health_days"])

In [ ]:
# BMI
df["bmi"] = round(df["bmi_x100"]/100,2)
df = df.drop("bmi_x100", axis=1)

In [ ]:
# Sex at birth
df["sex"] = df["sex"].replace({
    1: "Male",
    2: "Female"
})

In [87]:
# Age group
age_map = {
    1: "18-24",
    2: "25-29",
    3: "30-34",
    4: "35-39",
    5: "40-44",
    6: "45-49",
    7: "50-54",
    8: "55-59",
    9: "60-64",
    10: "65-69",
    11: "70-74",
    12: "75-79",
    13: "80+"
}

df["age_group"] = df["age_group"].map(age_map)

In [ ]:
# general health
genhlth_map = {
    1: "Excellent",
    2: "Very good",
    3: "Good",
    4: "Fair",
    5: "Poor"
}

df["general_health_label"] = df["general_health"].replace(genhlth_map)
df.loc[df["general_health_label"].isin([7, 9]), "general_health"] = np.nan
df = df.drop("general_health", axis=1)

In [ ]:
# blood pressure: suggestion for ML: use both during pregnancy and borderline as yes
df["high_blood_pressure_label"] = df["high_blood_pressure"].replace({
    1: "Yes",
    2: "Yes, during pregnancy",
    3: "No",
    4: "No, but Borderline",
    7: np.nan,
    9: np.nan
})
df = df.drop("high_blood_pressure", axis=1)

In [97]:
# diabetes: suggestion for ML: use both during pregnancy and borderline as yes
df["diabetes_label"] = df["diabetes"].replace({
    1: "Yes",
    2: "Yes, during pregnancy",
    3: "No",
    4: "No, but Borderline",
    7: np.nan,
    9: np.nan
})
df = df.drop("diabetes", axis=1)

In [106]:
# Alcoholdays/month

def alc_days_per_month(val):
    if val in [777, 999]:
        return np.nan
    elif val == 888:
        return 0
    elif 1 <= val <= 30:
        return val  # already monthly
    elif 101 <= val <= 199:
        # weekly drinking: subtract 100 to get days/week, multiply by 4
        return round((val - 100) * 4.3)
    else:
        return np.nan  # other unexpected codes

df["alcohol_days_month"] = df["alcohol_days_per_month"].apply(alc_days_per_month)
df = df.drop("alcohol_days_per_month", axis=1)

In [107]:
df.sample(6)

,ever_heart_attack,high_blood_pressure,high_cholesterol,ever_smoked_100_cigs,exercise_past_30_days,age_group,sex,poor_physical_health_days,poor_mental_health_days,activity_limited_health_days,...,skin_cancer_history,copd_history,kidney_disease_history,stroke_history,current_smoker,bmi,general_health_label,high_blood_pressure_label,diabetes_label,alcohol_days_month
360462,0.0,3.0,2.0,0.0,1.0,25-29,Female,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21.61,Very good,No,No,NaN
212128,0.0,1.0,1.0,1.0,1.0,45-49,Female,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21.95,Good,Yes,No,0.0
179087,0.0,1.0,2.0,NaN,1.0,45-49,Female,NaN,2.0,NaN,...,1.0,1.0,0.0,0.0,NaN,NaN,Good,Yes,No,NaN
104246,0.0,2.0,2.0,0.0,0.0,35-39,Female,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,Good,"Yes, during pregnancy",No,0.0
305286,0.0,1.0,2.0,0.0,0.0,45-49,Male,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,24.86,Very good,Yes,No,NaN
60209,0.0,3.0,2.0,0.0,1.0,25-29,Male,3.0,7.0,3.0,...,0.0,0.0,0.0,0.0,0.0,20.18,Good,No,No,0.0

In [77]:
df.shape

(433323, 20)

In [78]:
# drop rows with missing label
df = df.dropna(subset=["ever_heart_attack"])

In [79]:
df.shape

(430755, 20)

In [108]:
df.to_csv("../data/brfss_2023_heart_risk_clean.csv", index=False)